//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbstractDevelop.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Menu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Menu() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AbstractDevelop.Properties.Menu", typeof(Menu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Очистить всё.
        /// </summary>
        internal static string ClearAll {
            get {
                return ResourceManager.GetString("ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Очистить окно вывода.
        /// </summary>
        internal static string ClearDebug {
            get {
                return ResourceManager.GetString("ClearDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отладка.
        /// </summary>
        internal static string Debug {
            get {
                return ResourceManager.GetString("Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пауза.
        /// </summary>
        internal static string DebugPause {
            get {
                return ResourceManager.GetString("DebugPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начать.
        /// </summary>
        internal static string DebugStart {
            get {
                return ResourceManager.GetString("DebugStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Шаг.
        /// </summary>
        internal static string DebugStep {
            get {
                return ResourceManager.GetString("DebugStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Остановить.
        /// </summary>
        internal static string DebugStop {
            get {
                return ResourceManager.GetString("DebugStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Правка.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Копировать.
        /// </summary>
        internal static string EditCopy {
            get {
                return ResourceManager.GetString("EditCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы_резать.
        /// </summary>
        internal static string EditCut {
            get {
                return ResourceManager.GetString("EditCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Вставить.
        /// </summary>
        internal static string EditPaste {
            get {
                return ResourceManager.GetString("EditPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Применить.
        /// </summary>
        internal static string EditRedo {
            get {
                return ResourceManager.GetString("EditRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Отменить.
        /// </summary>
        internal static string EditUndo {
            get {
                return ResourceManager.GetString("EditUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Файл.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Закрыть файл.
        /// </summary>
        internal static string FileClose {
            get {
                return ResourceManager.GetString("FileClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Выход.
        /// </summary>
        internal static string FileExit {
            get {
                return ResourceManager.GetString("FileExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Создать.
        /// </summary>
        internal static string FileNew {
            get {
                return ResourceManager.GetString("FileNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Открыть.
        /// </summary>
        internal static string FileOpen {
            get {
                return ResourceManager.GetString("FileOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить.
        /// </summary>
        internal static string FileSave {
            get {
                return ResourceManager.GetString("FileSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить как.
        /// </summary>
        internal static string FileSaveAs {
            get {
                return ResourceManager.GetString("FileSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Справка.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на О программе.
        /// </summary>
        internal static string HelpAbout {
            get {
                return ResourceManager.GetString("HelpAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Содержание.
        /// </summary>
        internal static string HelpContent {
            get {
                return ResourceManager.GetString("HelpContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Примеры.
        /// </summary>
        internal static string HelpSamples {
            get {
                return ResourceManager.GetString("HelpSamples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Формат чисел.
        /// </summary>
        internal static string NumberFormat {
            get {
                return ResourceManager.GetString("NumberFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отображать редактор кода.
        /// </summary>
        internal static string ShowCodeEditor {
            get {
                return ResourceManager.GetString("ShowCodeEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отображать окно вывода.
        /// </summary>
        internal static string ShowDebugOutput {
            get {
                return ResourceManager.GetString("ShowDebugOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отображать редактор памяти.
        /// </summary>
        internal static string ShowMemoryEditor {
            get {
                return ResourceManager.GetString("ShowMemoryEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отображать редактор регистров.
        /// </summary>
        internal static string ShowRegisterEditor {
            get {
                return ResourceManager.GetString("ShowRegisterEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Инструменты.
        /// </summary>
        internal static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Схема RISC R8.
        /// </summary>
        internal static string ToolsSchema {
            get {
                return ResourceManager.GetString("ToolsSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тестировать программу.
        /// </summary>
        internal static string ToolsTesting {
            get {
                return ResourceManager.GetString("ToolsTesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Вид.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Двоичный.
        /// </summary>
        internal static string ViewBinary {
            get {
                return ResourceManager.GetString("ViewBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Шестнадцатеричный.
        /// </summary>
        internal static string ViewHex {
            get {
                return ResourceManager.GetString("ViewHex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Восьмеричный.
        /// </summary>
        internal static string ViewOctal {
            get {
                return ResourceManager.GetString("ViewOctal", resourceCulture);
            }
        }
    }
}
