//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbstractDevelop.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AbstractDevelop.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Применить.
        /// </summary>
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отменить.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Английский (en).
        /// </summary>
        internal static string EnglishLang {
            get {
                return ResourceManager.GetString("EnglishLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Язык:.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для изменения языка требуется перезапуск программы.
        /// </summary>
        internal static string LanguageChangeWarning {
            get {
                return ResourceManager.GetString("LanguageChangeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выполнение команд было начато.
        /// </summary>
        internal static string MachineStarted {
            get {
                return ResourceManager.GetString("MachineStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выполнение было завершено. Общее время выполнения: {0}.
        /// </summary>
        internal static string MachineStopped {
            get {
                return ResourceManager.GetString("MachineStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проект AbstractDevelop|*.adp|Файл проекта в формате JSON|*.json.
        /// </summary>
        internal static string ProjectFileFilter {
            get {
                return ResourceManager.GetString("ProjectFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Русский (ru).
        /// </summary>
        internal static string RussianLang {
            get {
                return ResourceManager.GetString("RussianLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Примеры не найдены! Попробуйте скачать другую сборку..
        /// </summary>
        internal static string SamplesNotFoundMessage {
            get {
                return ResourceManager.GetString("SamplesNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Схема RISC R8.
        /// </summary>
        internal static string SchemaViewTitle {
            get {
                return ResourceManager.GetString("SchemaViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на System (Default).
        /// </summary>
        internal static string SystemLang {
            get {
                return ResourceManager.GetString("SystemLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тест не пройден: &quot;{0}&quot;.
        /// </summary>
        internal static string TestFailed {
            get {
                return ResourceManager.GetString("TestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Набор тестов|*.test|Файл JSON|*.json.
        /// </summary>
        internal static string TestFileFilter {
            get {
                return ResourceManager.GetString("TestFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [полный набор инструкций].
        /// </summary>
        internal static string TestInstructionBase {
            get {
                return ResourceManager.GetString("TestInstructionBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось загрузить указанный файл. Возможно, он имеет неверный формат.
        /// </summary>
        internal static string TestLoadingException {
            get {
                return ResourceManager.GetString("TestLoadingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тест пройден успешно.
        /// </summary>
        internal static string TestSucces {
            get {
                return ResourceManager.GetString("TestSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка тестирования: &quot;{0}&quot;.
        /// </summary>
        internal static string TestSystemError {
            get {
                return ResourceManager.GetString("TestSystemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тестов не пройдено: {0}.
        /// </summary>
        internal static string TestSystemFailed {
            get {
                return ResourceManager.GetString("TestSystemFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все тесты пройдены успешно.
        /// </summary>
        internal static string TestSystemPassed {
            get {
                return ResourceManager.GetString("TestSystemPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить текущий проект?.
        /// </summary>
        internal static string UnsavedDataMessage {
            get {
                return ResourceManager.GetString("UnsavedDataMessage", resourceCulture);
            }
        }
    }
}
